# lang.py

STRINGS = {
    'zh': {
        'language_code': 'zh-TW',
        # main.py
        'CONFIG_NOT_FOUND': "[致命錯誤] 找不到 config.toml 檔案，請確認檔案是否存在。",
        'CONFIG_READ_SUCCESS': "[配置] 成功從命令行參數讀取 ngrok Token。",
        'CONFIG_READ_FAIL': "[配置] 警告：無法從命令行或 config.toml 讀取 ngrok Token。ngrok 將無法啟動。",
        'UPDATE_START': "\n--- [背景更新] 開始更新資料 ---",
        'UPDATE_DONE': "--- [背景更新] 資料更新完畢，原始活躍號碼 {raw_count} 個，初始篩選後 {filtered_count} 個。",
        'UPDATE_NEXT': "--- [背景更新] 將在 {seconds} 秒後再次更新 ---",
        'FILTER_UPDATED': "[篩選] 設定已更新: 模式={mode}, 包含={include}, 排除={exclude}",
        'POST_REQUEST_ERROR': "[錯誤] 處理 POST 請求時發生錯誤: {e}",
        'INITIALIZING': "正在初始化...",
        'CHECKING_DRIVER': "[*] 正在檢查並安裝 ChromeDriver...",
        'DRIVER_READY': "[*] ChromeDriver 服務已就緒。",
        'NGROK_REMINDER': "如果只想在本地端執行的話，請確認 config.toml 中的 ngrok_auth_token 為空字串 ''。",
        'NGROK_NOT_SET': "\033[91m[注意] ngrok Authtoken 未設定。\033[0m",
        'RUN_LOCAL_MODE': "將以本地模式運行 Flask 服務。",
        'INSTALL_DEPS': "請確保您已安裝所有必要的套件。建議執行:",
        'APP_STARTING': "程式正在啟動...",
        'TARGET_SITES': "目標網站列表: {urls}",
        'TARGET_COUNTRY': "目標國家: {country}",
        'LOCAL_URL': " * 本地網址: http://127.0.0.1:{port}",
        'PUBLIC_URL': " * 手機請訪問此公開網址: \033[92m{url}\033[0m",
        'BACKGROUND_UPDATE_INFO': "程式會在背景每 {minutes} 分鐘自動抓取一次最新資料。",
        'KEEP_WINDOW_OPEN_NGROK': "\n\033[91m重要：請保持此視窗開啟，關閉後公開網址將會失效。\033[0m",
        'NGROK_FAIL': "\n[!] ngrok 連線失敗，請檢查您的 Authtoken 或網路狀態: {e}",
        'FALLBACK_LOCAL': "將回退到本地模式運行 Flask 服務。",
        'APP_STARTING_LOCAL': "程式正在啟動 (本地模式)...",
        'KEEP_WINDOW_OPEN_LOCAL': "\n\033[91m重要：請保持此視窗開啟。\033[0m",

        # scraper_core.py
        'ADBLOCK_MISSING': "[*] 廣告攔截外掛不存在，正在從 GitHub 下載...",
        'ADBLOCK_INSTALLED': "[*] 廣告攔截外掛已成功安裝至: {path}",
        'ADBLOCK_DOWNLOAD_FAIL': "\n[!] 下載廣告攔截外掛失敗: {e}",
        'ADBLOCK_BAD_ZIP': "\n[!] 下載的檔案非有效的 ZIP 檔案。",
        'ADBLOCK_UNKNOWN_ERROR': "\n[!] 安裝廣告攔截外掛時發生未知錯誤: {e}",
        'ADBLOCK_LOAD_WARN': "[!] 警告：廣告攔截外掛目錄不存在，瀏覽器將在無攔截模式下運行。",
        'SMS_CONTENT_ENCRYPTED': " 【注意：內容可能被網站加密，請在瀏覽器中確認】",
        'CANNOT_READ_SMS': "無法讀取簡訊內容。",
        'CHECKING_NUMBER': "    [THREAD] 檢查號碼: {number} ...",
        'CHECKING_NUMBER_TEMP': "    [THREAD] 檢查號碼 (Temp-Number): {number} ...",
        'SELENIUM_READ_FAIL': "  -> \033[91mSelenium 讀取失敗: {e}\033[0m",
        'SELENIUM_TIMEOUT_ERROR': "  -> Selenium 讀取時發生超時或錯誤: {e}",
        'CHECK_NUMBER_FAIL': "  -> 檢查 {number} 失敗: {e}",
        'FOUND_ACTIVE_NUMBER': "  -> \033[92m找到活躍號碼 (最新訊息: {time})\033[0m",
        'INACTIVE_NUMBER': "  -> 不活躍 (最新訊息: {time})",
        'NO_MESSAGE_ROWS': "  -> 找不到訊息列。",
        'SEARCHING_NUMBERS_SELENIUM': "[*] 正在使用 Selenium 搜尋 {country} 國碼的號碼...",
        'SEARCHING_NUMBERS_BASE_URL': "[*] 正在使用 Selenium 搜尋 {url} 的號碼...",
        'TARGET_COUNTRY_PAGE': "[*] 目標國家頁面: {url}",
        'TARGET_COUNTRY_PAGE_TEMP': "[*] 目標國家頁面 (Temp-Number): {url}",
        'LOADING_COUNTRY_PAGE': "[*] 正在載入國家頁面以取得號碼清單...",
        'LOADING_COUNTRY_PAGE_TEMP': "[*] 正在載入國家頁面以取得號碼清單 (temp-number.com)...",
        'WAITING_CLOUDFLARE': "[*] 正在等待 Cloudflare 驗證...",
        'CLOUDFLARE_PASS': "[*] Cloudflare 驗證通過，頁面已載入。",
        'WAITING_PAGE_LOAD_TEMP': "[*] 正在等待 temp-number.com 頁面載入...",
        'PAGE_LOADED_PARSING': "[*] 頁面載入完畢，開始解析號碼...",
        'NO_NUMBERS_FOUND_ON_PAGE': "[!] 在國家頁面上找不到任何號碼。網站結構可能已更改或載入失敗。 ",
        'NO_NUMBERS_FOUND_ON_PAGE_TEMP': "[!] 在 temp-number.com 上找不到任何號碼連結。",
        'FOUND_NUMBERS_CONCURRENT_CHECK': "[*] 成功找到 {count} 個號碼，開始併發檢查...",
        'LOAD_COUNTRY_PAGE_FAIL': "\n[!] 載入國家頁面失敗: {e}",
        'LOAD_COUNTRY_PAGE_GENERAL_ERROR': "\n[!] 載入國家頁面發生一般錯誤: {e}",
        'LOAD_MAIN_PAGE_ATTEMPT_FAIL': "\n[!] 第 {attempt} 次嘗試載入主頁面或等待元素時發生錯誤: {e}",
        'NO_NUMBERS_AFTER_RETRIES': "[!] 在 3 次嘗試後，仍然無法在主頁上找到任何號碼。",
        'FOUND_LINK_SUCCESS': "[*] 第 {attempt} 次嘗試成功找到號碼連結。",
        'NO_LINK_ON_ATTEMPT': "[!] 第 {attempt} 次嘗試在主頁上找不到任何號碼。",
        'LOAD_MAIN_PAGE_GENERAL_ERROR': "\n[!] 載入主頁面發生一般錯誤: {e}",
        'LOAD_MAIN_PAGE_GENERAL_ERROR_TEMP': "\n[!] 載入 temp-number.com 主頁面或等待元素時發生錯誤: {e}",
        'WRITING_DEBUG_FILE': "\n--- 正在將頁面原始碼寫入 {path} (偵錯用) ---",
        'WRITE_DEBUG_FILE_DONE': "--- 寫入完成 ---",
        'WRITE_DEBUG_FILE_ERROR': "--- 寫入偵錯檔案時發生錯誤: {e} ---",
        'SEARCH_COMPLETE': "\n[*] 搜尋完畢。總共找到 {count} 個活躍號碼。",
        'SEARCH_COMPLETE_TEMP': "\n[*] temp-number.com 搜尋完畢。總共找到 {count} 個活躍號碼。",
        'TRAVERSING_SITES_START': "[*] 開始遍歷 {count} 個目標網站...",
        'PROCESSING_SITE': "\n--- 正在處理網站: {url} ---",
        'PARSER_NOT_FOUND': "[!] 警告：找不到為 {url} 設定的解析器。 ",
        'PROCESS_SITE_ERROR': "[!] 處理 {url} 時發生錯誤: {e}",
        'ALL_SITES_DONE': "\n[*] 所有網站處理完畢，總共從 {count} 個網站中收集到 {total} 個活躍號碼。 ",

        # Web Interface (index.html)
        'WEB_TITLE': "活躍簡訊號碼與關鍵字篩選",
        'WEB_H1': "活躍簡訊號碼",
        'WEB_INFO_REFRESH': "頁面每 60 秒自動刷新。上次資料更新於 {last_updated} (每 {minutes} 分鐘更新一次資料)。",
        'WEB_INFO_DISPLAYING': "<br>當前顯示 **{filtered_count}** 個號碼 (總活躍數: {total_count})。",
        'WEB_FILTER_TITLE': "關鍵字篩選設定",
        'WEB_INCLUDE_LABEL': "必須包含的關鍵字 (逗號分隔):",
        'WEB_INCLUDE_PLACEHOLDER': "例如: google, code, verify",
        'WEB_EXCLUDE_LABEL': "必須排除的關鍵字 (逗號分隔):",
        'WEB_EXCLUDE_PLACEHOLDER': "例如: crypto, loan, promo",
        'WEB_MODE_LABEL': "篩選模式:",
        'WEB_MODE_CONTAINS': "包含 (顯示包含任一包含關鍵字的訊息)",
        'WEB_MODE_EXCLUDES': "排除 (僅顯示不含任何排除關鍵字的訊息)",
        'WEB_MODE_BOTH': "包含 + 排除 (需同時滿足兩項)",
        'WEB_MODE_NONE': "不篩選 (顯示所有活躍號碼)",
        'WEB_APPLY_FILTER_BUTTON': "應用篩選器",
        'WEB_LOADING': "讀取中。。。請稍後。。。正在努力爬蟲中。",
        'WEB_ERROR': "讀取中。。。讀取網站時發生錯誤，請稍後再試。爬蟲可能已被封鎖或初始化失敗。",
        'WEB_NO_RESULTS': "目前沒有符合篩選條件的號碼。"
    },
    'en': {
        'language_code': 'en',
        # main.py
        'CONFIG_NOT_FOUND': "[FATAL] config.toml not found. Please ensure the file exists.",
        'CONFIG_READ_SUCCESS': "[Config] Successfully read ngrok Token from command-line arguments.",
        'CONFIG_READ_FAIL': "[Config] Warning: Could not read ngrok Token from command-line or config.toml. ngrok will not start.",
        'UPDATE_START': "\n--- [Background Update] Starting data update ---",
        'UPDATE_DONE': "--- [Background Update] Data update complete. Found {raw_count} raw active numbers, {filtered_count} after initial filtering.",
        'UPDATE_NEXT': "--- [Background Update] Will update again in {seconds} seconds ---",
        'FILTER_UPDATED': "[Filter] Settings updated: Mode={mode}, Include={include}, Exclude={exclude}",
        'POST_REQUEST_ERROR': "[Error] An error occurred while processing POST request: {e}",
        'INITIALIZING': "Initializing...",
        'CHECKING_DRIVER': "[*] Checking and installing ChromeDriver...",
        'DRIVER_READY': "[*] ChromeDriver service is ready.",
        'NGROK_REMINDER': "If you only want to run locally, please ensure ngrok_auth_token is an empty string '' in config.toml.",
        'NGROK_NOT_SET': "\033[91m[Warning] ngrok Authtoken is not set.\033[0m",
        'RUN_LOCAL_MODE': "Running Flask service in local mode.",
        'INSTALL_DEPS': "Please ensure you have installed all necessary packages. It is recommended to run:",
        'APP_STARTING': "Application starting...",
        'TARGET_SITES': "Target website list: {urls}",
        'TARGET_COUNTRY': "Target country: {country}",
        'LOCAL_URL': " * Local URL: http://127.0.0.1:{port}",
        'PUBLIC_URL': " * Public URL for mobile access: \033[92m{url}\033[0m",
        'BACKGROUND_UPDATE_INFO': "The application will automatically fetch new data in the background every {minutes} minutes.",
        'KEEP_WINDOW_OPEN_NGROK': "\n\033[91mImportant: Keep this window open. The public URL will become invalid upon closing.\033[0m",
        'NGROK_FAIL': "\n[!] ngrok connection failed. Please check your Authtoken or network status: {e}",
        'FALLBACK_LOCAL': "Falling back to run Flask service in local mode.",
        'APP_STARTING_LOCAL': "Application starting (local mode)...",
        'KEEP_WINDOW_OPEN_LOCAL': "\n\033[91mImportant: Please keep this window open.\033[0m",

        # scraper_core.py
        'ADBLOCK_MISSING': "[*] Adblocker extension not found, downloading from GitHub...",
        'ADBLOCK_INSTALLED': "[*] Adblocker extension successfully installed to: {path}",
        'ADBLOCK_DOWNLOAD_FAIL': "\n[!] Failed to download adblocker extension: {e}",
        'ADBLOCK_BAD_ZIP': "\n[!] Downloaded file is not a valid ZIP file.",
        'ADBLOCK_UNKNOWN_ERROR': "\n[!] An unknown error occurred while installing the adblocker extension: {e}",
        'ADBLOCK_LOAD_WARN': "[!] Warning: Adblocker extension directory not found. The browser will run without ad blocking.",
        'SMS_CONTENT_ENCRYPTED': " [Note: Content may be encrypted by the website, please verify in browser]",
        'CANNOT_READ_SMS': "Could not read SMS content.",
        'CHECKING_NUMBER': "    [THREAD] Checking number: {number} ...",
        'CHECKING_NUMBER_TEMP': "    [THREAD] Checking number (Temp-Number): {number} ...",
        'SELENIUM_READ_FAIL': "  -> \033[91mSelenium read failed: {e}\033[0m",
        'SELENIUM_TIMEOUT_ERROR': "  -> Selenium timeout or error during read: {e}",
        'CHECK_NUMBER_FAIL': "  -> Failed to check {number}: {e}",
        'FOUND_ACTIVE_NUMBER': "  -> \033[92mFound active number (Last message: {time})\033[0m",
        'INACTIVE_NUMBER': "  -> Inactive (Last message: {time})",
        'NO_MESSAGE_ROWS': "  -> Could not find message rows.",
        'SEARCHING_NUMBERS_SELENIUM': "[*] Searching for numbers in country code {country} using Selenium...",
        'SEARCHING_NUMBERS_BASE_URL': "[*] Searching for numbers at {url} using Selenium...",
        'TARGET_COUNTRY_PAGE': "[*] Target country page: {url}",
        'TARGET_COUNTRY_PAGE_TEMP': "[*] Target country page (Temp-Number): {url}",
        'LOADING_COUNTRY_PAGE': "[*] Loading country page to get number list...",
        'LOADING_COUNTRY_PAGE_TEMP': "[*] Loading country page to get number list (temp-number.com)...",
        'WAITING_CLOUDFLARE': "[*] Waiting for Cloudflare verification...",
        'CLOUDFLARE_PASS': "[*] Cloudflare verification passed, page loaded.",
        'WAITING_PAGE_LOAD_TEMP': "[*] Waiting for temp-number.com page to load...",
        'PAGE_LOADED_PARSING': "[*] Page loaded, starting to parse numbers...",
        'NO_NUMBERS_FOUND_ON_PAGE': "[!] No numbers found on the country page. Site structure may have changed or page failed to load.",
        'NO_NUMBERS_FOUND_ON_PAGE_TEMP': "[!] No number links found on temp-number.com.",
        'FOUND_NUMBERS_CONCURRENT_CHECK': "[*] Successfully found {count} numbers, starting concurrent checks...",
        'LOAD_COUNTRY_PAGE_FAIL': "\n[!] Failed to load country page: {e}",
        'LOAD_COUNTRY_PAGE_GENERAL_ERROR': "\n[!] A general error occurred while loading the country page: {e}",
        'LOAD_MAIN_PAGE_ATTEMPT_FAIL': "\n[!] Attempt {attempt} to load main page or wait for element failed: {e}",
        'NO_NUMBERS_AFTER_RETRIES': "[!] Could not find any numbers on the main page after 3 attempts.",
        'FOUND_LINK_SUCCESS': "[*] Successfully found number links on attempt {attempt}.",
        'NO_LINK_ON_ATTEMPT': "[!] Could not find any numbers on the main page on attempt {attempt}.",
        'LOAD_MAIN_PAGE_GENERAL_ERROR': "\n[!] A general error occurred while loading the main page: {e}",
        'LOAD_MAIN_PAGE_GENERAL_ERROR_TEMP': "\n[!] An error occurred while loading the temp-number.com main page or waiting for elements: {e}",
        'WRITING_DEBUG_FILE': "\n--- Writing page source to {path} (for debugging) ---",
        'WRITE_DEBUG_FILE_DONE': "--- Write complete ---",
        'WRITE_DEBUG_FILE_ERROR': "--- An error occurred while writing the debug file: {e} ---",
        'SEARCH_COMPLETE': "\n[*] Search complete. Found a total of {count} active numbers.",
        'SEARCH_COMPLETE_TEMP': "\n[*] temp-number.com search complete. Found a total of {count} active numbers.",
        'TRAVERSING_SITES_START': "[*] Starting to traverse {count} target websites...",
        'PROCESSING_SITE': "\n--- Processing site: {url} ---",
        'PARSER_NOT_FOUND': "[!] Warning: No parser configured for {url}.",
        'PROCESS_SITE_ERROR': "[!] An error occurred while processing {url}: {e}",
        'ALL_SITES_DONE': "\n[*] All sites processed. Collected a total of {total} active numbers from {count} websites.",

        # Web Interface (index.html)
        'WEB_TITLE': "Active SMS Numbers & Keyword Filter",
        'WEB_H1': "Active SMS Numbers",
        'WEB_INFO_REFRESH': "Page auto-refreshes every 60 seconds. Last data update at {last_updated} (updates every {minutes} minutes).",
        'WEB_INFO_DISPLAYING': "<br>Currently displaying **{filtered_count}** numbers (Total active: {total_count}).",
        'WEB_FILTER_TITLE': "Keyword Filter Settings",
        'WEB_INCLUDE_LABEL': "Keywords to Include (comma-separated):",
        'WEB_INCLUDE_PLACEHOLDER': "e.g., google, code, verify",
        'WEB_EXCLUDE_LABEL': "Keywords to Exclude (comma-separated):",
        'WEB_EXCLUDE_PLACEHOLDER': "e.g., crypto, loan, promo",
        'WEB_MODE_LABEL': "Filter Mode:",
        'WEB_MODE_CONTAINS': "Contains (Show messages with any included keyword)",
        'WEB_MODE_EXCLUDES': "Excludes (Show messages without any excluded keyword)",
        'WEB_MODE_BOTH': "Contains + Excludes (Must satisfy both)",
        'WEB_MODE_NONE': "No Filter (Show all active numbers)",
        'WEB_APPLY_FILTER_BUTTON': "Apply Filter",
        'WEB_LOADING': "Loading... Please wait... Scraping in progress.",
        'WEB_ERROR': "Loading... An error occurred while fetching from websites. Please try again later. The scraper might be blocked or failed to initialize.",
        'WEB_NO_RESULTS': "No numbers currently match the filter criteria."
    }
}

def get_lang(language_code='zh'):
    """Gets the language dictionary for the given code, defaulting to 'zh'."""
    return STRINGS.get(language_code, STRINGS['zh'])
