name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Wow! Is this your first issue? 🎉 Fantastic! We're thrilled to see you engaging with our project. Thanks for taking the time to report this – your feedback fuels our growth! We'll take a look soon. 😊"
        pr-message: "Awesome! Is this your first Pull Request? 🤩 We're absolutely thrilled by your contribution! Thank you for investing your time to make our project even better. We'll review it shortly and can't wait to collaborate! ✨"